# Generated by Django 4.1.4 on 2022-12-17 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_giftcards'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('content', models.CharField(max_length=250)),
                ('status', models.CharField(choices=[('available', 'available'), ('pending', 'pending'), ('deleted', 'deleted')], max_length=200)),
            ],
        ),
    ]
