# Generated by Django 4.1.4 on 2022-12-19 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_notifications'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntroOffers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('desc', models.CharField(max_length=300)),
                ('off', models.PositiveIntegerField()),
                ('image', models.ImageField(null=True, upload_to='images/')),
                ('validity', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('available', 'available'), ('unavailable', 'unavailble'), ('expired', 'expired'), ('redeemed', 'redeemed')], max_length=300)),
            ],
        ),
    ]
