# Generated by Django 4.1.4 on 2022-12-20 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_blogs'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('phone', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=200)),
                ('company', models.CharField(max_length=300)),
                ('subject', models.CharField(max_length=300)),
                ('question', models.TextField()),
            ],
        ),
    ]
