# Generated by Django 4.1.4 on 2022-12-20 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_contactus_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactus',
            name='status',
        ),
    ]
