# Generated by Django 4.1.4 on 2022-12-21 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0017_wishlist_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='status',
            field=models.CharField(choices=[('Wishlisted', 'Wishlisted'), ('Removed', 'Removed')], default='Wishlisted', max_length=300),
        ),
    ]
