# Generated by Django 4.1.4 on 2022-12-21 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0018_alter_wishlist_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='question',
            new_name='messsage',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='company',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='phone',
        ),
    ]
