# Generated by Django 4.1.2 on 2022-12-21 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0019_rename_question_contactus_messsage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='timeslots',
        ),
        migrations.AddField(
            model_name='services',
            name='timeslots',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.timeslots'),
        ),
    ]
