# Generated by Django 4.1.2 on 2022-12-21 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0020_remove_services_timeslots_services_timeslots'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='timeslots',
        ),
        migrations.AddField(
            model_name='services',
            name='timeslots',
            field=models.ManyToManyField(null=True, to='customer.timeslots'),
        ),
    ]
