# Generated by Django 4.1.4 on 2022-12-21 10:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('owner', '0006_remove_package_timeslot'),
        ('customer', '0020_profilemanage_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyMemberships',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('booked', 'booked'), ('expired', 'expired')], default='booked', max_length=200)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owner.memberships')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
