# Generated by Django 4.1.4 on 2022-12-21 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0021_mymemberships'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymemberships',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
