# Generated by Django 4.1.4 on 2022-12-22 04:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0006_remove_package_timeslot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer', '0022_mymemberships_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyPackages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('booked', 'booked'), ('expired', 'expired')], default='booked', max_length=200)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owner.package')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
