# Generated by Django 4.1.4 on 2022-12-22 05:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer', '0023_mypackages'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyGiftcards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('booked', 'booked'), ('expired', 'expired')], default='booked', max_length=200)),
                ('giftcard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.giftcards')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
