# Generated by Django 4.1.2 on 2022-12-22 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0021_remove_services_timeslots_services_timeslots'),
        ('customer', '0024_mygiftcards'),
    ]

    operations = [
    ]
