# Generated by Django 4.1.2 on 2022-12-22 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0025_merge_20221222_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='timeslots',
            field=models.ManyToManyField(null=True, related_name='service_slots', to='customer.timeslots'),
        ),
    ]
