# Generated by Django 4.1.2 on 2022-12-22 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0027_alter_services_timeslots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='timeslots',
            field=models.ManyToManyField(to='customer.timeslots'),
        ),
    ]
