# Generated by Django 4.1.2 on 2022-12-22 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0028_alter_services_timeslots'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('price', models.PositiveIntegerField(null=True)),
                ('desc', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(null=True, upload_to='images/')),
                ('status', models.BooleanField(default=True, null=True)),
                ('timeslot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.timeslots')),
            ],
        ),
        migrations.AlterField(
            model_name='mypackages',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.package'),
        ),
    ]
