# Generated by Django 4.1.2 on 2022-12-22 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0029_package_alter_mypackages_package'),
    ]

    operations = [
        migrations.CreateModel(
            name='Memberships',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('validity', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField(null=True)),
                ('desc', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('status', models.BooleanField(default=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('Paid', 'Paid'), ('In Process', 'In Process'), ('Pending', 'Pending'), ('Failed', 'Failed')], max_length=300)),
                ('amount', models.PositiveIntegerField()),
                ('currency', models.CharField(max_length=100)),
                ('details', models.CharField(max_length=250)),
                ('type', models.CharField(max_length=120)),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='mymemberships',
            name='membership',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.memberships'),
        ),
    ]
