# Generated by Django 4.1.2 on 2022-12-22 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0030_memberships_transaction_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilemanage',
            name='company',
        ),
        migrations.RemoveField(
            model_name='profilemanage',
            name='email',
        ),
        migrations.RemoveField(
            model_name='services',
            name='availability',
        ),
        migrations.AlterField(
            model_name='booking',
            name='timeslot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.timeslots'),
        ),
        migrations.DeleteModel(
            name='BookedSlot',
        ),
    ]
