# Generated by Django 4.1.4 on 2022-12-22 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0032_profilemanage_image_alter_profilemanage_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilemanage',
            name='image',
        ),
    ]
