# Generated by Django 4.1.2 on 2022-12-22 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0033_remove_profilemanage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslots',
            name='availability',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
