# Generated by Django 4.1.4 on 2022-12-23 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0035_alter_contactus_messsage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='messsage',
            field=models.TextField(),
        ),
    ]
