# Generated by Django 4.1.4 on 2022-12-26 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0039_servicereview_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilemanage',
            name='address',
        ),
        migrations.RemoveField(
            model_name='profilemanage',
            name='name',
        ),
        migrations.AddField(
            model_name='profilemanage',
            name='address_lane1',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='profilemanage',
            name='address_lane2',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='profilemanage',
            name='country',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profilemanage',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='profilemanage',
            name='first_name',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='profilemanage',
            name='language',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='profilemanage',
            name='last_name',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='profilemanage',
            name='residence_no',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profilemanage',
            name='state',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='profilemanage',
            name='zip_code',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='profilemanage',
            name='contactno',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='timeslots',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
