# Generated by Django 4.1.4 on 2022-12-27 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0040_remove_profilemanage_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilemanage',
            name='address_lane2',
        ),
        migrations.RemoveField(
            model_name='profilemanage',
            name='residence_no',
        ),
    ]
