# Generated by Django 4.1.4 on 2022-12-27 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0041_remove_profilemanage_address_lane2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilemanage',
            old_name='address_lane1',
            new_name='address',
        ),
    ]
