# Generated by Django 4.1.4 on 2022-12-27 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0042_rename_address_lane1_profilemanage_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='messsage',
            new_name='message',
        ),
    ]
