# Generated by Django 4.1.4 on 2022-12-28 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0045_services_striked_off_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='striked_off_cost',
            field=models.PositiveIntegerField(default=99),
        ),
    ]
