# Generated by Django 4.1.4 on 2022-12-29 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0047_alter_servicereview_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('giftcard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.mygiftcards')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.mymemberships')),
            ],
        ),
    ]
