# Generated by Django 4.1.4 on 2022-12-29 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0048_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='giftcard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.giftcards'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='membership',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.memberships'),
        ),
    ]
