# Generated by Django 4.1.4 on 2022-12-29 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0050_cart_user_alter_cart_giftcard_alter_cart_membership'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='introoffer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.introoffers'),
        ),
    ]
