# Generated by Django 4.1.4 on 2022-12-29 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0052_myintrooffers'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.package'),
        ),
    ]
