# Generated by Django 4.1.4 on 2022-12-30 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0053_cart_package'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicereview',
            name='rating',
        ),
    ]
