# Generated by Django 4.1.4 on 2022-12-30 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0055_services_rating_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='rating',
            field=models.IntegerField(default=5),
        ),
    ]
