# Generated by Django 4.0.6 on 2022-12-31 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0057_alter_services_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='exclusive',
            field=models.BooleanField(default=False),
        ),
    ]
