# Generated by Django 4.0.6 on 2022-12-31 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0063_alter_recentlyviewed_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recentlyviewed',
            name='service',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.services'),
        ),
    ]
