# Generated by Django 4.0.6 on 2023-01-02 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0066_alter_recentlyviewed_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='status',
            field=models.CharField(choices=[('unread', 'unread'), ('viewed', 'viewed')], default='unread', max_length=200),
        ),
    ]
