# Generated by Django 4.1.4 on 2023-01-03 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0068_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.currency'),
        ),
        migrations.AddField(
            model_name='giftcards',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.currency'),
        ),
        migrations.AddField(
            model_name='introoffers',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.currency'),
        ),
        migrations.AddField(
            model_name='package',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.currency'),
        ),
        migrations.AddField(
            model_name='services',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.currency'),
        ),
    ]
