# Generated by Django 4.1.4 on 2023-01-03 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0069_booking_currency_giftcards_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberships',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.currency'),
        ),
    ]
