# Generated by Django 4.1.4 on 2023-01-03 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0070_memberships_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='currency_type',
            field=models.CharField(choices=[('$', '$'), ('Rs', 'Rs')], default='$', max_length=20),
        ),
    ]
