# Generated by Django 4.1.4 on 2023-01-04 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0072_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='email',
            field=models.EmailField(max_length=200, null=True),
        ),
    ]
