# Generated by Django 4.1.4 on 2023-01-04 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0073_alter_subscription_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='giftcards',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='introoffers',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='memberships',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='package',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='services',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='currency',
        ),
    ]
