# Generated by Django 4.1.4 on 2023-01-04 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0074_remove_booking_currency_remove_giftcards_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='currency',
            name='currency_type',
            field=models.CharField(default='$', max_length=20),
        ),
    ]
