# Generated by Django 4.1.4 on 2023-01-04 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0075_currency_status_alter_currency_currency_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='currency_type',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='currency',
            name='status',
            field=models.BooleanField(null=True),
        ),
    ]
