# Generated by Django 4.1.4 on 2023-01-05 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0076_alter_currency_currency_type_alter_currency_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerOpenings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('image', models.ImageField(upload_to='images/')),
                ('desc', models.TextField()),
            ],
        ),
    ]
