# Generated by Django 4.0.6 on 2023-01-06 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0078_careers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careers',
            name='age',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='careers',
            name='contact_personal_employer',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='careers',
            name='contr_subs',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='careers',
            name='convicted',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='careers',
            name='currently_employed',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='careers',
            name='drive_license',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='careers',
            name='ever_applied',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='careers',
            name='ever_employed',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='careers',
            name='law_status',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='careers',
            name='transportation',
            field=models.CharField(max_length=300),
        ),
    ]
