# Generated by Django 4.0.6 on 2023-01-06 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0080_alter_careers_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careers',
            name='applied_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='careers',
            name='areas_improve',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='careers',
            name='client_count',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='careers',
            name='college',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='careers',
            name='college_compl_year',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='careers',
            name='college_course',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='careers',
            name='company_awareness',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='careers',
            name='contact_personal_employer',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='careers',
            name='contr_subs',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='careers',
            name='contr_to_comp',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='careers',
            name='convicted',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='careers',
            name='cosmet_compl_year',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='careers',
            name='cosmet_course',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='careers',
            name='cosmet_school',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='careers',
            name='current_salary',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='careers',
            name='currently_employed',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='careers',
            name='cuurent_work_hours',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='careers',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='careers',
            name='drive_license_exp',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='careers',
            name='employed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='careers',
            name='ever_applied',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='careers',
            name='ever_applied_yes',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='careers',
            name='ever_employed',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='careers',
            name='ever_employed_yes',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='careers',
            name='exp_address',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='careers',
            name='exp_company',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='careers',
            name='exp_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='careers',
            name='exp_job',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='careers',
            name='exp_phone',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='careers',
            name='exp_rate',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='careers',
            name='exp_reason_leave',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='careers',
            name='exp_supervisor',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='careers',
            name='exp_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='careers',
            name='fri_hrs',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='careers',
            name='ind_bg',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='careers',
            name='ind_crazy',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='careers',
            name='ind_exp',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='careers',
            name='ind_exp_years',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='careers',
            name='ind_expect',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='careers',
            name='ind_goal_plan',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='careers',
            name='ind_goals',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='careers',
            name='ind_how_no_spa',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='careers',
            name='ind_how_spa',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='careers',
            name='ind_offer',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='careers',
            name='ind_pr_job_exp',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='careers',
            name='ind_pr_job_leave',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='careers',
            name='ind_where_see',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='careers',
            name='likely_work_hours',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='careers',
            name='massage_compl_year',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='careers',
            name='massage_course',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='careers',
            name='massage_school',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='careers',
            name='mon_hrs',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='careers',
            name='need_salary',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='careers',
            name='other_compl_year',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='careers',
            name='other_course',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='careers',
            name='other_school',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='careers',
            name='phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='careers',
            name='reference',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='careers',
            name='sat_hrs',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='careers',
            name='school',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='careers',
            name='shool_compl_year',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='careers',
            name='special_training',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='careers',
            name='strengths',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='careers',
            name='sun_hrs',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='careers',
            name='thu_hrs',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='careers',
            name='tue_hrs',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='careers',
            name='university',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='careers',
            name='want_salary',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='careers',
            name='wed_hrs',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
