# Generated by Django 4.0.6 on 2023-01-06 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0081_alter_careers_applied_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careers',
            name='age',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='careers',
            name='drive_license',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='careers',
            name='law_status',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='careers',
            name='transportation',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
