# Generated by Django 4.0.6 on 2023-01-07 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0085_eductaiondetails_experiencedetails_extradetails_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemanage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
