# Generated by Django 4.0.6 on 2023-01-07 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0086_profilemanage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslots',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timeslots',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
