# Generated by Django 4.0.6 on 2023-01-07 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0088_remove_timeslots_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslots',
            name='time',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='timeslots',
            name='status',
            field=models.CharField(max_length=30),
        ),
    ]
