# Generated by Django 4.1.2 on 2023-01-17 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0089_timeslots_time_alter_timeslots_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('booked', 'booked'), ('payment-pending', 'payment-pending'), ('booking-confirmed', 'booking-confirmed'), ('cancelled', 'cancelled'), ('completed', 'completed')], default='payment-pending', max_length=200),
        ),
    ]
