# Generated by Django 4.1.2 on 2023-01-18 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0090_alter_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(max_length=300),
        ),
    ]
