# Generated by Django 4.1.5 on 2023-03-03 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0096_servicecart'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecart',
            name='cost',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicecart',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicecart',
            name='time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='servicecart',
            name='beautician',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
