# Generated by Django 4.1.5 on 2023-03-06 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0098_cart_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslots',
            name='status',
            field=models.CharField(choices=[('available', 'available'), ('pending', 'pending'), ('booked', 'booked')], default='available', max_length=30),
        ),
        migrations.CreateModel(
            name='AddOns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('cost', models.PositiveIntegerField(null=True)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(max_length=500, null=True)),
                ('image', models.ImageField(null=True, upload_to='images/')),
                ('duration', models.DurationField(blank=True, null=True)),
                ('category', models.ManyToManyField(to='customer.categories')),
            ],
        ),
    ]
