# Generated by Django 4.1.5 on 2023-03-06 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0099_alter_timeslots_status_addons'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecart',
            name='addons',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.addons'),
        ),
    ]
