# Generated by Django 4.1.2 on 2023-03-09 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0101_alter_servicecart_status_serviceorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('booking_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('beautician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.beautician')),
                ('services', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.services')),
                ('timeslot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.timeslots')),
            ],
        ),
    ]
