# Generated by Django 4.1.2 on 2023-03-09 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0103_rename_booking_date_forbooking_bookingdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forbooking',
            old_name='beautician',
            new_name='docter',
        ),
        migrations.AddField(
            model_name='forbooking',
            name='phone',
            field=models.CharField(default=2, max_length=10),
            preserve_default=False,
        ),
    ]
