# Generated by Django 4.1.2 on 2023-03-10 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0105_forbooking_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forbooking',
            old_name='user',
            new_name='usern',
        ),
    ]
