# Generated by Django 4.1.4 on 2022-12-21 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0005_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='timeslot',
        ),
    ]
