# Generated by Django 4.1.2 on 2022-12-22 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0030_memberships_transaction_and_more'),
        ('owner', '0007_delete_package_alter_transaction_amount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Memberships',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
